# Generated by Django 5.1.7 on 2025-04-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroutine',
            name='user',
        ),
        migrations.RemoveField(
            model_name='examroutine',
            name='user',
        ),
    ]
