# Generated by Django 5.1.7 on 2025-04-25 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_mynote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examroutine',
            name='date',
        ),
        migrations.RemoveField(
            model_name='examroutine',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='examroutine',
            name='time',
        ),
        migrations.AddField(
            model_name='examroutine',
            name='course_name',
            field=models.CharField(default='Untitled Exam', max_length=100),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='exam_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
