# Generated by Django 5.1.7 on 2025-06-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0009_alter_classroutine_user_alter_examroutine_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
