# Generated by Django 5.1.7 on 2025-06-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0011_alter_classroutine_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
