# Generated by Django 5.1.7 on 2025-06-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0012_activity_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
