# Generated by Django 5.1.7 on 2025-06-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0016_alter_activity_date_alter_activity_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
    ]
