# Generated by Django 5.1.7 on 2025-06-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0017_remove_activity_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_time',
        ),
    ]
