# Generated by Django 5.1.7 on 2025-06-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0018_remove_activity_duration_remove_activity_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
