# Generated by Django 5.1.7 on 2025-06-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0019_alter_activity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='due_date',
        ),
    ]
