# Generated by Django 5.1.5 on 2025-06-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0020_remove_activity_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.CharField(blank=True, default='#general', max_length=100),
        ),
    ]
