# Generated by Django 5.1.7 on 2025-06-21 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0020_remove_activity_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.CharField(blank=True, default='#general', max_length=100),
        ),
    ]
